name: Build Heltec v4 Firmware

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Clone Repo
        uses: actions/checkout@v6

      - name: Setup Build Environment
        uses: ./.github/actions/setup-build-environment

      - name: Build Firmwares
        env:
          FIRMWARE_VERSION: v1.16.0u
        run: /usr/bin/env bash build.sh build-firmware heltec_v4_companion_radio_ble

      - name: Upload Workflow Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: heltec_v4_companion_radio_ble
          path: out
